/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

int *
add_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  arr[]={1,3,5,7,11,13,17,19,23,29,31,37,41};
	static int  result;

	printf("Query(%d, %d): \n", arr[argp->a], arr[argp->b]);
        result = arr[argp->a] + arr[argp->b];
	return &result;
}
